[project]
name = "agentic-rag-llamaindex"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.13.0",
    "dashscope>=1.22.2",
    "fastapi>=0.136.1",
    "llama-index>=0.14.22",
    "llama-index-core>=0.14.22",
    "llama-index-embeddings-huggingface>=0.7.0",
    "llama-index-llms-dashscope>=0.6.1",
    "llama-index-llms-openai-like>=0.7.2",
    "llama-index-readers-file>=0.6.0",
    "llama-index-vector-stores-milvus>=1.1.0",
    "minio>=7.2.20",
    "neo4j>=6.2.0",
    "pydantic-settings>=2.14.1",
    "pymilvus>=2.4.2",
    "pypdf>=6.11.0",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.28",
    "redis>=5.2.1",
    "sentence-transformers>=5.5.0",
    "transformers>=5.8.1",
    "uvicorn[standard]>=0.47.0",
    "torch==2.6.0",
    "torchvision==0.21.0",
    "torchaudio==2.6.0",
    "flagembedding>=1.4.0",
    "llama-index-observability-otel>=0.6.2",
    "opentelemetry-exporter-otlp-proto-http>=1.42.0",
    "openinference-instrumentation-llama-index>=4.4.2",
    "opentelemetry-sdk>=1.42.0",
    "opentelemetry-instrumentation-fastapi>=0.63b0",
    "arize-phoenix>=15.11.1",
    "arize-phoenix-otel>=0.16.1",
    "pydantic>=2.13.4",
]
[tool.uv.sources]
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
torchaudio = { index = "pytorch-cu124" }

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
